language: node_js
node_js:
- "4"
- "node"
sudo: false
cache:
  directories:
  - node_modules
script: bash ./deploy.sh
env:
  global:
  - ENCRYPTION_LABEL: "c632016e8c09"
  - COMMIT_AUTHOR_EMAIL: ""
install:
- npm install
- npm update
- node index.js
